name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_ci.yml"

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}  # e.g. sit722acr25155.azurecr.io
  ACR_NAME:         ${{ secrets.ACR_NAME }}          # e.g. sit722acr25155
  IMAGE_TAG:        ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Sanity check env
        run: |
          set -e
          echo "ACR_NAME=$ACR_NAME"
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"
          test -n "$ACR_NAME" && test -n "$ACR_LOGIN_SERVER"

      - name: Login to Azure Container Registry
        run: az acr login --name "$ACR_NAME"

      - name: Build and Push Frontend Image
        working-directory: frontend
        run: |
          docker build -t "$ACR_LOGIN_SERVER/frontend:latest" .
          docker push "$ACR_LOGIN_SERVER/frontend:latest"

      - name: Logout from Azure
        if: always()
        run: az logout
